name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Determine relevant changes
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'src/**'
              - 'package.json'
              - 'bun.lock'
              - 'svelte.config.*'
              - 'vite.config.*'
              - 'tsconfig*.json'
              - 'vitest*.ts'
              - 'tailwind.config.*'
              - 'static/**'

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: SvelteKit sync
        run: bunx --yes svelte-kit sync

      - name: Build application
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
          retention-days: 1

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: SvelteKit sync
        run: bunx --yes svelte-kit sync

      - name: Run unit tests
        run: bunx --yes vitest run --config vitest.config.unit.ts

      - name: Run integration tests
        run: bun run test:integration

      - name: Generate unit coverage report
        run: bunx --yes vitest run --config vitest.config.unit.ts --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        with:
          fail_ci_if_error: false
          verbose: true

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript check
        run: bun run check

      - name: Run Svelte check
        run: bun run check:watch --once || bun run check
