name: Preview Site

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - '**/*.svelte'
      - '**/*.ts'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  approval:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment:
      name: preview
    steps:
      - run: echo "Awaiting approval for PR preview deploy"

  build:
    if: github.event.action != 'closed'
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build SvelteKit site (static)
        env:
          KIT_ADAPTER: static
          BASE_PATH: kite/pr-preview/pr-${{ github.event.pull_request.number }}
        run: bun run build

  deploy:
    if: github.event.action != 'closed'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PR Preview to gh-pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Remove PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove